document.write("<table class=\"menu\">");
document.write("<tr>");
document.write("<td>");
document.write("<nav class=\"main-nav\">");
document.write("<ul class=\"main-nav-ul\">");
document.write("<li><a href=\"#\">Home</a></li>");
document.write("<li class=\"has-sub\"><a>Call for Contributions<span class=\"sub-arrow\"></span></a>");
document.write("<ul>");
document.write("<li><a href=\"#\">Main Track</a></li>");
document.write("<li><a href=\"#\">Industry Track</a></li>");
document.write("<li><a href=\"#\">Workshops</a></li>");
document.write("<li><a href=\"#\">Tutorials</a></li>");
document.write("<li><a href=\"#\">Student Forum</a></li>");
document.write("<li><a href=\"#\">Fast Abstract</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class=\"has-sub\"><a>Committees<span class=\"sub-arrow\"></span></a>");
document.write("<ul>");
document.write("<li><a href=\"#\">Organizing Committe</a></li>");
document.write("<li><a href=\"#\">Steering Committe</a></li>");
document.write("<li><a href=\"#\">Program Committe</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class=\"has-sub\"><a>Awards<span class=\"sub-arrow\"></span></a>");
document.write("<ul>");
document.write("<li><a href=\"#\">Best Paper Award</a></li>");
document.write("<li><a href=\"#\">Carter Award</a></li>");
document.write("<li><a href=\"#\">Jean Claude Laprie Award</a></li>");
document.write("<li><a href=\"#\">IEEE ISI Award</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class=\"has-sub\"><a>Accepted Contributions<span class=\"sub-arrow\"></span></a>");
document.write("<ul>");
document.write("<li><a href=\"#\">Main Track</a></li>");
document.write("<li><a href=\"#\">Industry Track</a></li>");
document.write("<li><a href=\"#\">Workshops</a></li>");
document.write("<li><a href=\"#\">Tutorials</a></li>");
document.write("<li><a href=\"#\">Student Forum</a></li>");
document.write("<li><a href=\"#\">Fast Abstract</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li><a href=\"sponsors\">Sponsors</a></li>");
document.write("<li><a href=\"impostant_dates\">Important Dates</a></li>");
document.write("<li><a href=\"registration\">Registration</a></li>");
document.write("<li><a href=\"previous_conferences\">Previous Conferences</a></li>");
document.write("<li><a href=\"news\">News</a></li>");
document.write("<li><a href=\"travel\">Travel</a></li>");
document.write("<li><a href=\"twitter\">Twitter</a></li>");
document.write("</ul>");
document.write("</nav>");
	
document.write("</td>");
	
document.write("</tr>");
document.write("</table>");
