document.write("<table class=\"menu\">");
document.write("<tr>");
document.write("<td>");
document.write("<nav class=\"main-nav\">");
document.write("<ul class=\"main-nav-ul\">");
document.write("<li><a>Home</a></li>");
document.write("<li class=\"has-sub\"><a>Call for Contributions<span class=\"sub-arrow\"></span></a>");
document.write("<ul>");
document.write("<li><a href=\"call_for_contributions/main_track\">Main Track</a></li>");
document.write("<li><a href=\"call_for_contributions/industry_track\">Industry Track</a></li>");
document.write("<li><a href=\"call_for_contributions/workshops\">Workshops</a></li>");
document.write("<li><a href=\"call_for_contributions/tutorials\">Tutorials</a></li>");
document.write("<li><a href=\"call_for_contributions/student_forum\">Student Forum</a></li>");
document.write("<li><a href=\"call_for_contributions/industry_track\">Fast Abstract</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class=\"has-sub\"><a>Committees<span class=\"sub-arrow\"></span></a>");
document.write("<ul>");
document.write("<li><a href=\"committees/organizing_committee\">Organizing Committee</a></li>");
document.write("<li><a href=\"committees/steering_committee\">Steering Committee</a></li>");
document.write("<li><a href=\"committees/program_committee\">Program Committee</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class=\"has-sub\"><a>Awards<span class=\"sub-arrow\"></span></a>");
document.write("<ul>");
document.write("<li><a href=\"awards/best_paper_award\">Best Paper Award</a></li>");
document.write("<li><a href=\"awards/carter_award\">Carter Award</a></li>");
document.write("<li><a href=\"awards/jean_claude_laprie_award\">Jean Claude Laprie Award</a></li>");
document.write("<li><a href=\"awards/ieee_isi_award\">IEEE ISI Award</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class=\"has-sub\"><a>Accepted Contributions<span class=\"sub-arrow\"></span></a>");
document.write("<ul>");
document.write("<li><a href=\"accepted_contributions/main_track\">Main Track</a></li>");
document.write("<li><a href=\"accepted_contributions/industry_track\">Industry Track</a></li>");
document.write("<li><a href=\"accepted_contributions/workshops\">Workshops</a></li>");
document.write("<li><a href=\"accepted_contributions/tutorials\">Tutorials</a></li>");
document.write("<li><a href=\"accepted_contributions/student_forum\">Student Forum</a></li>");
document.write("<li><a href=\"accepted_contributions/fast_abstract\">Fast Abstract</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li><a href=\"sponsors\">Sponsors</a></li>");
document.write("<li><a href=\"important_dates\">Important Dates</a></li>");
document.write("<li><a href=\"registration\">Registration</a></li>");
document.write("<li><a href=\"previous_conferences\">Previous Conferences</a></li>");
document.write("<li><a href=\"news\">News</a></li>");
document.write("<li><a href=\"travel\">Travel</a></li>");
document.write("<li><a href=\"twitter\">Twitter</a></li>");
document.write("</ul>");
document.write("</nav>");
	
document.write("</td>");
	
document.write("</tr>");
document.write("</table>");
